[package]
name = "int-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
alloy= { version = "0.11.1", features = ["full", "node-bindings", "json-rpc", "rpc-client", "signer-local", "k256", "rand", "rlp"] }

[dev-dependencies]
rand = "0.8"
tokio = "1.45.0"
